Tutorial 1: explore Numpy library to Analyze the Data
the pythone package numpy , which stands for "numerical python",


In [138]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [139]:
import numpy as np

In [140]:
print(np.__version__)

2.3.5


In [141]:
a = [1, 2, 3, 4, 5]

find diffrence between pythone list vs numpy array  

python list is store any datatypes vs numpy store only same datatype
slower vs faster
pythone own data structure used so no need of library


In [142]:
x= np.array(a)
x

array([1, 2, 3, 4, 5])

In [143]:
#1D array
x=np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [144]:
x = np.random.rand(5)
x

array([0.74489091, 0.76087515, 0.09186629, 0.99900171, 0.54910108])

In [145]:
x = np.random.rand(5,16)
x

array([[0.87974776, 0.51572251, 0.1000689 , 0.58403799, 0.42159948,
        0.57363963, 0.24265309, 0.35440785, 0.18146136, 0.51053689,
        0.27810087, 0.07201388, 0.34758504, 0.37518363, 0.77591833,
        0.28495743],
       [0.44206737, 0.49715186, 0.23616354, 0.91327461, 0.9586133 ,
        0.43009611, 0.51292762, 0.48726915, 0.0369452 , 0.99010387,
        0.19357751, 0.93858726, 0.3790599 , 0.95259591, 0.5507351 ,
        0.19682401],
       [0.96718725, 0.85614098, 0.00371322, 0.45390118, 0.12553677,
        0.4135764 , 0.55624686, 0.23109093, 0.3143229 , 0.8610134 ,
        0.24420559, 0.00199089, 0.27869232, 0.34339372, 0.72827764,
        0.0476739 ],
       [0.95557194, 0.16750503, 0.09176837, 0.54297583, 0.74079841,
        0.95037694, 0.77975896, 0.42985654, 0.67764117, 0.59847954,
        0.18732057, 0.64193872, 0.5206973 , 0.66807845, 0.48510288,
        0.08701475],
       [0.75354147, 0.65892166, 0.0911418 , 0.92897036, 0.41277284,
        0.36768143, 0.53434033, 

In [146]:
#2D array
y=np.array([[1,2,3],[4,5,6],[7,8,9],[6,7,8]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [6 7 8]]


In [147]:
np.random.rand(3,4)

array([[0.94215798, 0.03373843, 0.45582777, 0.2186993 ],
       [0.60489984, 0.34320728, 0.76830086, 0.62035285],
       [0.2206131 , 0.15585999, 0.88101401, 0.49709469]])

In [148]:
#3d array
z=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[8,9,9]],[[7,8,9],[8,9,9]]])
print(z)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [8 9 9]]

 [[7 8 9]
  [8 9 9]]]


In [149]:
a =np.zeros((3,4),dtype=bool)
a

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [150]:
a=np.ones((5,5),dtype=bool)
a

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [151]:
a = np.full((5,5),4)
a

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [152]:
a=np.eye(4,5,dtype=int)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


In [153]:
a=4*np.eye(4,5,dtype=int)
print(a)

[[4 0 0 0 0]
 [0 4 0 0 0]
 [0 0 4 0 0]
 [0 0 0 4 0]]


In [154]:
print("shape of a",a.shape)

shape of a (4, 5)


In [155]:
z.ndim

3

In [156]:
a.shape

(4, 5)

In [157]:
a.size

20

In [158]:
a.ndim

2

In [159]:
x.argmax()

np.int64(25)

In [160]:
x.min()

np.float64(0.0019908891422474317)

In [161]:
x.max()

np.float64(0.9901038738385906)

In [162]:
x.mean()

np.float64(0.47632006199153293)

why numpy is faster than list
where numpy mainly use

NumPy is faster because it works at low level (C language) and performs operations on whole arrays at once. It is mainly used for numerical and scientific calculations.

In [163]:
#2D array
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[9,8,7],[6,5,4],[3,2,1]])
print(a,b)
print(a+b)


[[1 2 3]
 [4 5 6]
 [7 8 9]] [[9 8 7]
 [6 5 4]
 [3 2 1]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]


Indexing is used to access elements in lists, arrays,strings , or other data structures.

python uses zero-based indexing (0 is the first element ).
Negatiive indexing allow access from the end of the structure.
In 2d arrays indexing requires row and column indices
Indexing is the processing of single element from a sequence using its position or index. 

In [164]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
b

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [166]:
b[0,0]

np.int64(9)

slicing  refers to the process of extracting a portion of an array or subset of array.

In [167]:
np.flip(a)


array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [168]:
np.flip(a)

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

Tutorial : 2 - Explore Pandas library to analyze  and manipulate data.
Description: Use Pandas library for data analysis and manipulation.

Dataset: Sample CSV file

Task: Load the dataset, perform data cleaning, manipulation (like sorting, filtering), and exploratory data analysis.


Import numpy and pandas library.
Define series with 3 elements.
Define a series with a custom index.
Fetch Series value and index.
Create DataFrame from list of Dict.
Create sample excel file in your computer with columns “name”, “Branch” and “Division”. Add atleast 5 records in excel file.  Read the excel file in .ipynb.
Explore Kaggle: Your Machine Learning and Data Science Community and UCI Machine Learning Repository for a dataset. Search iris dataset and download.
Read iris dataset from csv file format and findout no. of rows and columns.
 Perform the following operation on the iris dataset.
Fetch the first 5 and last 5 rows.
Find index.
Find column name and rename it with SepalLengthCm':'Sepal_Length','SepalWidthCm':'Sepal_Width','PetalLengthCm':'Petal_Length','PetalWidthCm':'Petal_Width'
replace "Iris-versicolor" with "versicolor", same way do for rest 2 categories.
Find Statistical description.
extract specific column.
add new column with condition.
drop added column.
select first row data.
select 51 to 55 rows
Apply conditional formatting.
print "virginica" with "Petal_Length" more than 6.
find duplicate values
Find basic information.
Find null value in dataset.
Download student_info dataset. Find null value from it. And fill null value using mean of that column.
Dataset Link: https://drive.google.com/drive/folders/1xTZizwH2onTZ8KpW1gttiFZ8SrY8RKOt?usp=sharing

Import adult data set from UCIML Adult - UCI Machine Learning Repository. And perform following task.
Find missing value. Find type of missing data.
Handle missing value.
12.

________________________________________________________________________

panda is the open source library for real world data analysis in python .
it is built on top of numpy
the basic data structures of pandas are series and data frame.
1.series : one dimentional labelled array
2.Dataframe:in pandas is a two-dimentional ,tabular data structure similar to a spreadsheet or sql table.
it consist of row and columns,where.

In [169]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [170]:
import numpy as np
import pandas as pd

In [171]:
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [172]:
s1=pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
s1


a    1
b    2
c    3
d    4
e    5
dtype: int64

find a difference between list ,1D numpy array,series

In [173]:
data = [{'Name ': 'jay ', 'marks':20}, {'Name ': 'ajay ', 'marks':22} , {'Name ': 'vijay ', }, {'Name ': 'sanjay ', 'marks':23},]
f1 = pd.DataFrame(data)
f1

Name   marks
0     jay    20.0
1    ajay    22.0
2   vijay     NaN
3  sanjay    23.0

In [174]:
f1.isna()

Name   marks
0  False  False
1  False  False
2  False   True
3  False  False

In [175]:
f1.isna().sum()

Name     0
marks    1
dtype: int64

In [176]:
type(data)

list

In [177]:
iris = pd.read_csv("iris.csv") #this is a dataset of iris flower

In [178]:
iris

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [179]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Sepal.Length  150 non-null    float64
 1   Sepal.Width   150 non-null    float64
 2   Petal.Length  150 non-null    float64
 3   Petal.Width   150 non-null    float64
 4   Species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [180]:
iris.isna().sum()

Sepal.Length    0
Sepal.Width     0
Petal.Length    0
Petal.Width     0
Species         0
dtype: int64

In [181]:
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [182]:
iris.tail()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [183]:
iris.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [184]:
iris = iris.rename(columns = {'Sepal.Length' : 'sepal_length', 'Sepal.Width': 'Sepal_Width', 'Petal.Length': 'Petal_Length','Petal.Width' : 'Petal_Width'})
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   Sepal_Width   150 non-null    float64
 2   Petal_Length  150 non-null    float64
 3   Petal_Width   150 non-null    float64
 4   Species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [185]:
iris['Species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [186]:
iris.replace("setosa","Setosa",inplace=True)
iris['Species'].unique()

array(['Setosa', 'versicolor', 'virginica'], dtype=object)

In [187]:
iris.describe()

sepal_length  Sepal_Width  Petal_Length  Petal_Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [188]:
iris[['Petal_Length','Petal_Width']]

Petal_Length  Petal_Width
0             1.4          0.2
1             1.4          0.2
2             1.3          0.2
3             1.5          0.2
4             1.4          0.2
..            ...          ...
145           5.2          2.3
146           5.0          1.9
147           5.2          2.0
148           5.4          2.3
149           5.1          1.8

[150 rows x 2 columns]

In [189]:
def yes_no(Sepal_Length):
    return 'YES' if Sepal_Length >= 5 else 'NO'
iris['Result'] = iris['sepal_length'].apply(yes_no)
iris

sepal_length  Sepal_Width  Petal_Length  Petal_Width    Species Result
0             5.1          3.5           1.4          0.2     Setosa    YES
1             4.9          3.0           1.4          0.2     Setosa     NO
2             4.7          3.2           1.3          0.2     Setosa     NO
3             4.6          3.1           1.5          0.2     Setosa     NO
4             5.0          3.6           1.4          0.2     Setosa    YES
..            ...          ...           ...          ...        ...    ...
145           6.7          3.0           5.2          2.3  virginica    YES
146           6.3          2.5           5.0          1.9  virginica    YES
147           6.5          3.0           5.2          2.0  virginica    YES
148           6.2          3.4           5.4          2.3  virginica    YES
149           5.9          3.0           5.1          1.8  virginica    YES

[150 rows x 6 columns]

In [190]:
iris.drop('Result',axis=1)

sepal_length  Sepal_Width  Petal_Length  Petal_Width    Species
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [191]:
iris[iris['Petal_Length'] > 5]

sepal_length  Sepal_Width  Petal_Length  Petal_Width     Species Result
83            6.0          2.7           5.1          1.6  versicolor    YES
100           6.3          3.3           6.0          2.5   virginica    YES
101           5.8          2.7           5.1          1.9   virginica    YES
102           7.1          3.0           5.9          2.1   virginica    YES
103           6.3          2.9           5.6          1.8   virginica    YES
104           6.5          3.0           5.8          2.2   virginica    YES
105           7.6          3.0           6.6          2.1   virginica    YES
107           7.3          2.9           6.3          1.8   virginica    YES
108           6.7          2.5           5.8          1.8   virginica    YES
109           7.2          3.6           6.1          2.5   virginica    YES
110           6.5          3.2           5.1          2.0   virginica    YES
111           6.4          2.7           5.3          1.9   virginica    YES
112           6.8          3.0           5.5          2.1   virginica    YES
114           5.8          2.8           5.1          2.4   virginica    YES
115           6.4          3.2           5.3          2.3   virginica    YES
116           6.5          3.0           5.5          1.8   virginica    YES
117           7.7          3.8           6.7          2.2   virginica    YES
118           7.7          2.6           6.9          2.3   virginica    YES
120           6.9          3.2           5.7          2.3   virginica    YES
122           7.7          2.8           6.7          2.0   virginica    YES
124           6.7          3.3           5.7          2.1   virginica    YES
125           7.2          3.2           6.0          1.8   virginica    YES
128           6.4          2.8           5.6          2.1   virginica    YES
129           7.2          3.0           5.8          1.6   virginica    YES
130           7.4          2.8           6.1          1.9   virginica    YES
131           7.9          3.8           6.4          2.0   virginica    YES
132           6.4          2.8           5.6          2.2   virginica    YES
133           6.3          2.8           5.1          1.5   virginica    YES
134           6.1          2.6           5.6          1.4   virginica    YES
135           7.7          3.0           6.1          2.3   virginica    YES
136           6.3          3.4           5.6          2.4   virginica    YES
137           6.4          3.1           5.5          1.8   virginica    YES
139           6.9          3.1           5.4          2.1   virginica    YES
140           6.7          3.1           5.6          2.4   virginica    YES
141           6.9          3.1           5.1          2.3   virginica    YES
142           5.8          2.7           5.1          1.9   virginica    YES
143           6.8          3.2           5.9          2.3   virginica    YES
144           6.7          3.3           5.7          2.5   virginica    YES
145           6.7          3.0           5.2          2.3   virginica    YES
147           6.5          3.0           5.2          2.0   virginica    YES
148           6.2          3.4           5.4          2.3   virginica    YES
149           5.9          3.0           5.1          1.8   virginica    YES

In [192]:
iris[ (iris['Petal_Length'] > 6) & (iris['Species'] == "virginica") ]

sepal_length  Sepal_Width  Petal_Length  Petal_Width    Species Result
105           7.6          3.0           6.6          2.1  virginica    YES
107           7.3          2.9           6.3          1.8  virginica    YES
109           7.2          3.6           6.1          2.5  virginica    YES
117           7.7          3.8           6.7          2.2  virginica    YES
118           7.7          2.6           6.9          2.3  virginica    YES
122           7.7          2.8           6.7          2.0  virginica    YES
130           7.4          2.8           6.1          1.9  virginica    YES
131           7.9          3.8           6.4          2.0  virginica    YES
135           7.7          3.0           6.1          2.3  virginica    YES

1.read dataset student info.csv

In [193]:
students= pd.read_csv('student_info.csv')
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   study_hours    195 non-null    float64
 1   student_marks  200 non-null    float64
dtypes: float64(2)
memory usage: 3.3 KB


In [194]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   study_hours    195 non-null    float64
 1   student_marks  200 non-null    float64
dtypes: float64(2)
memory usage: 3.3 KB


In [195]:
students.columns

Index(['study_hours', 'student_marks'], dtype='object')

In [196]:
students.isna().sum()

study_hours      5
student_marks    0
dtype: int64

In [197]:
students['study_hours'] = students['student_marks'].fillna(students['study_hours'].mean())

In [198]:
students.isna().sum()

study_hours      0
student_marks    0
dtype: int64

In [199]:
pip install ucimlrepo

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [200]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
adult = fetch_ucirepo(id=2) 
  
# data (as pandas dataframes) 
X = adult.data.features 
y = adult.data.targets 
  
# metadata 
print(adult.metadata) 
  
# variable information 
print(adult.variables) 


{'uci_id': 2, 'name': 'Adult', 'repository_url': 'https://archive.ics.uci.edu/dataset/2/adult', 'data_url': 'https://archive.ics.uci.edu/static/public/2/data.csv', 'abstract': 'Predict whether annual income of an individual exceeds $50K/yr based on census data. Also known as "Census Income" dataset. ', 'area': 'Social Science', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 48842, 'num_features': 14, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Age', 'Income', 'Education Level', 'Other', 'Race', 'Sex'], 'target_col': ['income'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1996, 'last_updated': 'Tue Sep 24 2024', 'dataset_doi': '10.24432/C5XW20', 'creators': ['Barry Becker', 'Ronny Kohavi'], 'intro_paper': None, 'additional_info': {'summary': "Extraction was done by Barry Becker from the 1994 Census database.  A set of reasonably clean records was extracted using the fol

In [201]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             48842 non-null  int64 
 1   workclass       47879 non-null  object
 2   fnlwgt          48842 non-null  int64 
 3   education       48842 non-null  object
 4   education-num   48842 non-null  int64 
 5   marital-status  48842 non-null  object
 6   occupation      47876 non-null  object
 7   relationship    48842 non-null  object
 8   race            48842 non-null  object
 9   sex             48842 non-null  object
 10  capital-gain    48842 non-null  int64 
 11  capital-loss    48842 non-null  int64 
 12  hours-per-week  48842 non-null  int64 
 13  native-country  48568 non-null  object
dtypes: int64(6), object(8)
memory usage: 5.2+ MB


In [202]:
X.isna().sum()

age                 0
workclass         963
fnlwgt              0
education           0
education-num       0
marital-status      0
occupation        966
relationship        0
race                0
sex                 0
capital-gain        0
capital-loss        0
hours-per-week      0
native-country    274
dtype: int64

In [203]:
X.head()

age         workclass  fnlwgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital-gain  capital-loss  hours-per-week native-country  
0          2174             0              40  United-States  
1             0             0              13  United-States  
2             0             0              40  United-States  
3             0             0              40  United-States  
4             0             0              40           Cuba

In [204]:
model0 = computers['minutes'].mean()    
model1 = 10+12 * computers['minutes']
model2 = 6+18 * computers['units']  

KeyError: 'minutes'

In [ ]:
computers['model0'] = model0
computers['model1'] = model1    
computers['model2'] = model2

NameError: name 'model0' is not defined